### ISSUE TITLE
Creación de Pág. Principal

### ISSUE THREAD

**Issue by Argudo** [Argudo/EBZ#10]
Como usuario
Quiero una página principal tras iniciar sesión con información básica
Para acceder a todos las funcionalidades

**Comment by Argudo** [comment]
La página principal se lanzaría tras iniciar sesión y contendría las cuentas y últimas transacciones del usuario

**Comment by Argudo** [comment]
La información que aparecerá se dejara en forma de placeholder en espera de la creación de las entidades

**Comment by manupruiz** [comment]
Versión placeholder finalizada a la espera de conectar con las entities y de cambios estéticos finales

**Comment by saikora11** [comment]
Bug encontrado: Si el usuario no tiene ninguna cuenta asociada la página devuelve una excepcion
