### ISSUE TITLE
Creación Entity Cuenta

### ISSUE THREAD

**Issue by Argudo** [Argudo/EBZ#13]
Como desarrollador
Quiero una entidad cuenta
Para poder obtener información sobre ella

**Comment by saikora11** [comment]
Creado Entity Cuenta, Repository y Service
Service puede sufrir mejoras para añadirle más logica de negocio

**Comment by saikora11** [comment]
Actualización: Creado relación con cliente, creado método findByCliente

**Comment by manupruiz** [comment]
Bug encontrado: Se muestra cuenta aún estando eliminada (tiene fechaEliminación asignada).
