### ISSUE TITLE
Configuración de la base de datos

### ISSUE THREAD

**Issue by Argudo** [Argudo/EBZ#8]
Como desarrollador 
Quiero que el proyecto esté enlazado con la base de datos usando Spring
Para el desarrollo de las entidades

**Comment by saikora11** [comment]
NOTA: Para que la configuración funcione exitosamente debe haber un database creado llamado 'ebz' en MySql escuchando en el puerto 3306, siendo el user 'root' sin ningún password.

**Comment by Argudo** [comment]
Completado
